services:
  elasticsearch:
    image: elasticsearch:9.2.0
    container_name: elasticsearch_dev
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elastic_data_dev:/usr/share/elasticsearch/data

volumes:
  elastic_data_dev:
    driver: local