spring:
  h2:
    console:
      enabled: false
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.h2.Driver

  elasticsearch:
    uris: http://localhost:9200

  data:
    redis:
      host: localhost
      port: 6379
      repositories:
        enabled: true
      password: monolithPassword123

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    show-sql: false

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 150MB

  mvc:
    servlet:
      path: /api/v1

api:
  security:
    token:
      secret: ${JWT_SECRET}
      issuer: ${JWT_ISSUER}
      expiration-hours: ${JWT_EXPIRATION_HOURS}
    cookie:
      name: jwt-token
      secure: ${JWT_COOKIE_SECURE}

server:
  servlet:
    session:
      timeout: 30m

mercadoPago:
  accessToken: ${MERCADO_PAGO_ACCESS_TOKEN}
  notificationURL: ${MERCADO_PAGO_NOTIFICATION_URL}

aws:
  accessKeyId: ${AWS_ACCESS_KEY_ID}
  secretKey: ${AWS_SECRET_ACCESS_KEY}
  region: ${AWS_REGION}
  bucketName: ${AWS_S3_BUCKET_NAME}

  queues:
    model-created: ${AWS_SQS_MODEL_CREATED_QUEUE_URL}
    model-zip-completed: ${AWS_SQS_MODEL_ZIP_COMPLETED_QUEUE_URL}